version: "3"

services:
  redis:
    image: 'redis:alpine'
    command: redis-server --appendonly yes
    container_name: redis
    ports: 
      - "6379:6379"
    networks:
      - utils

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mercapp
    ports:
      - "27017:27017"
    networks:
      - utils

  mysql:
    container_name: mysql
    mem_limit: 1024m
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: store
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    networks:
      - utils

  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:alpine'
    ports:
      - "5672:5672"
    networks:
      - utils

networks:
  utils: 
    name: utils

