version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: mercapp
    ports:
      - "27017:27017"
    networks:
      - utils

networks:
  utils: 
    name: utils

