version: "3"

services:
  redis:
    image: 'redis:alpine'
    command: redis-server --appendonly yes --requirepass admin
    container_name: redis
    ports: 
      - "6379:6379"
    networks:
      - utils

networks:
  utils: 
    name: utils

